CREATE TABLE Channel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    channel_id BIGINT NOT NULL,
    FOREIGN KEY (channel_id) REFERENCES Channel(id) ON DELETE CASCADE
);